/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String boldAnsi = "\033[1m";
        String redAnsi = "\033[31m";
        String resetAnsi = "\033[0m";

        String title = "[팀 프로젝트 관리 시스템]";
        String line = "----------------------------";
        String[] menus = {"회원", "팀", "프로젝트", "게시판", "도움말", "종료"};

        Scanner scanner = new Scanner(System.in);

        System.out.println(boldAnsi + line + resetAnsi);
        System.out.println(boldAnsi + title + resetAnsi);

        for(int i = 0; i < menus.length; i++) {
            if(menus[i] == "종료") {
                System.out.printf("%s%d. %s\n", (boldAnsi + redAnsi), (i + 1), (menus[i] + resetAnsi));
            } else {
                System.out.printf("%d. %s\n", (i + 1), menus[i]);
            }
        }

        System.out.println(boldAnsi + line + resetAnsi);

        int menuNo;
        System.out.print("> ");
        while (scanner.hasNext()) {
            try {
                menuNo = scanner.nextInt();

                if(menuNo >= 1 && menuNo <= menus.length) {
                    if(menus[menuNo - 1] == "종료") {
                        break;
                    }
                    System.out.println(menus[menuNo -1]);
                } else {
                    System.out.println("메뉴 번호가 옳지 않습니다.");

                }
            } catch (Exception e) {
                System.out.println("메뉴 번호가 옳지 않습니다.");
                scanner.next();
            }

            System.out.print("> ");
        }

        scanner.close();
        System.out.println("종료합니다.");
    }
}